---
companyName: Valley Pro Contractor
tagline: example tagline 2018
googleMapLink: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50938.48240122875!2d-120.87455956412253!3d37.06570026251416!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80917f1be37a62b7%3A0x6172e10ec1c8cd94!2sFreedom+West+Real+Estate+Group+Inc.!5e0!3m2!1sen!2sus!4v1526508465803
address:
  street: 519 Fairmont Dr.
  address2: ''
  city: Los Banos
  zip: '93635'
  state: CA
phones:
- title: Human Resources
  number: 1 (800) 123 4567
- title: Billing
  number: 1 (800) 123 4567
emails:
- title: Human Resources
  address: example@valleypro.com
socialMedia:
  facebook:
    url: ''
  twitter:
    handle: ''
    url: ''
  instagram:
    handle: ''
    url: ''
  googlePlus:
    handle: ''
    url: ''
  linkedIn:
    url: ''
